
stages:
  - test

mariadb:
  stage: test
  image: python:3.9
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: gitdatatest
    MYSQL_ROOT_PASSWORD: root
  script:
    - source tests/setup_container.sh
    - nosetests --with-doctest --with-coverage --cover-package=gitdata -vx gitdata/utils.py tests/unittests

postgres:
  stage: test
  image: python:3.9
  services:
    - postgres:latest
  variables:
    POSTGRES_PASSWORD: password
    GITDATA_TEST_DATABASE_HOST: postgres
  script:
    - pip install .
    - pip install -r tests/requirements.txt
    - nosetests -vx tests/unittests/test_database.py:TestPostgreSQLDatabase
