
stages:
  - test

before_script:
    - pip install .
    - pip install -r tests/requirements.txt

general:
  stage: test
  image: python:3.9
  services:
    - postgres:latest
  variables:
    POSTGRES_PASSWORD: password
    GITDATA_TEST_DATABASE_HOST: postgres
  script:
    - nosetests gitdata $(ls tests/unittests/test_*.py | grep -v database)

mariadb:
  stage: test
  image: python:3.9
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: gitdatatest
    MYSQL_ROOT_PASSWORD: root
    GITDATA_TEST_DATABASE_HOST: mariadb
    GITDATA_TEST_DATABASE_USER: root
    GITDATA_TEST_DATABASE_PASSWORD: root
  script:
    - nosetests tests/unittests/test_database.py:TestMySQLDatabase

postgres:
  stage: test
  image: python:3.9
  services:
    - postgres:latest
  variables:
    POSTGRES_PASSWORD: password
    GITDATA_TEST_DATABASE_HOST: postgres
  script:
    - nosetests tests/unittests/test_database.py:TestPostgreSQLDatabase
